### ISSUE TITLE
[feature]: Instances and Executions should show a read-only workflow

### ISSUE THREAD

**Issue by marko-kriskovic** [bytechefhq/bytechef#1027]
## Instances

When the specific workflow of a project instance is clicked, a sheet is opened. We need to display a read-only variant of the selected workflow at the specific version.

![image](https://github.com/bytechefhq/bytechef/assets/24564752/ec43de83-f164-420c-99ae-4db0b6ca0a6c)

## Executions

When a specific workflow execution is clicked we need to display a read-only variant of the selected workflow at the specific version in the sheet that opens.

![image](https://github.com/bytechefhq/bytechef/assets/24564752/83c657a9-55fb-4512-807d-cc773f25ce1d)

**Comment by ivicac** [comment]
@marko-kriskovic this is actually missing feature
