### ISSUE TITLE
[task] Replace quill and quill-mention  with tiptap

### ISSUE THREAD

**Issue by ivicac** [bytechefhq/bytechef#1062]
https://github.com/quill-mention/quill-mention or replace quill with tiptap:

1. https://github.com/ueberdosis/tiptap
2. https://tiptap.dev/docs/editor/extensions/nodes/mention

**Comment by kresimir-coko** [comment]
Couldn't get this working, asked in their Q&A so waiting for a response - https://github.com/quill-mention/quill-mention/discussions/400

**Comment by kresimir-coko** [comment]
Related https://github.com/bytechefhq/bytechef/issues/1515
- onChange being invoked on render is causing the value to be reset
