### ISSUE TITLE
[bug]: XML Helper object list doesn't incorporate all types 

### ISSUE THREAD

**Issue by marko-kriskovic** [bytechefhq/bytechef#1075]
### Describe the bug

when I create an object list, dynamic properties or task and try to add property of type OBJECT, TASK or DYNAMIC_PROPERTIES, nothing is showing

### Steps To Reproduce

1. XML helper component
2. Convert to XML string

- [x] a)
3. select Object in type
4. add object

- [x] b)
3. select Array in type
4. add dynamic properties
5. add object in dynamic properties

- [x] c)
3. select Array in type
4. add object
5. add object in object

- [x] d)
3. select Array in type
4. add array

- [x] e)
3. select Array in type
4. add string
5. press the "x" next to the field

### Expected behavior

they should be removed form the list, or made to work

### Version

latest

### OS

ubuntu

**Comment by kresimir-coko** [comment]
@marko-kriskovic ja ne vidim DYNAMIC_PROPERTIES u listi ponuđenih tipova

**Comment by kresimir-coko** [comment]
https://github.com/bytechefhq/bytechef/tree/889-parameters
