### ISSUE TITLE
[bug]: XML Helper Integer can't be filled

### ISSUE THREAD

**Issue by marko-kriskovic** [bytechefhq/bytechef#1076]
### Describe the bug

integer in arrays doesn't have a switch input type button, so I can't type numbers

### Steps To Reproduce

1. XML helper component
2. Convert to XML string
3. select Array in type
4. add INTEGER
5. try to type something

### Expected behavior

you should be able to type something manually

### Version

latest

### OS

ubuntu

**Comment by kresimir-coko** [comment]
https://github.com/bytechefhq/bytechef/pull/1082
