### ISSUE TITLE
[bug]: data pill panel wont open

### ISSUE THREAD

**Issue by marko-kriskovic** [bytechefhq/bytechef#1085]
### Describe the bug

when I click on an input that should have data pill input, the data pill panel wont open
![image](https://github.com/bytechefhq/bytechef/assets/150443197/5d06674f-1ae1-4871-9016-efb68e63a321)

### Steps To Reproduce

1. logger component
2. any action
3. click on text input

### Expected behavior

the data pill panel should open when I click on the input

### Version

latest

### OS

ubuntu

**Comment by kresimir-coko** [comment]
https://github.com/bytechefhq/bytechef/pull/1086
