### ISSUE TITLE
[bug]: can't create a OAuth2 connection

### ISSUE THREAD

**Issue by marko-kriskovic** [bytechefhq/bytechef#1089]
### Describe the bug

when I try to create a connection, an error is thrown. oAuth2AppMap is empty.
![Screenshot from 2024-05-21 11-22-22](https://github.com/bytechefhq/bytechef/assets/150443197/e6b9c8e4-cf3f-4b99-97d9-ca145ca67470)

### Steps To Reproduce

1. any component that has a OAuth2 connection
2. try to make a connection

### Expected behavior

users should be able to connect with OAuth2

### Version

latest

### OS

ubuntu

**Comment by kresimir-coko** [comment]
https://github.com/bytechefhq/bytechef/pull/1091
