### ISSUE TITLE
[feature]: Improve the UI showing Connection details inside the NodeDetailsPanel Connection tab

### ISSUE THREAD

**Issue by kresimir-coko** [bytechefhq/bytechef#1142]
### Tell us about the problem you're trying to solve

![image](https://github.com/bytechefhq/bytechef/assets/24564752/b2114620-27f5-49f7-ab6e-db882ebad60b)

Visual hierarchy of `connection parameters` and the overall design is not up to standards.

### Describe the solution you’d like

`Connection parameters` should be a lower-level heading, and the content under it should be stretched out to fit the entire width of the panel. The keys and values should be visually different, perhaps by using a different color or size for the text.

### Describe the alternative you’ve considered or used

-

**Comment by joshmurdock** [comment]
Hello! I am going to see if I can fix this issue.
