### ISSUE TITLE
[feature]: Add an empty option for both Select and ComboBox so that the user can reset an optional value

### ISSUE THREAD

**Issue by marko-kriskovic** [bytechefhq/bytechef#1158]
### Describe the bug

When I change an option on some first select, another select that is depended on that select changes its values. When there is only one value on the second select, it is automatically changed to that value. I cannot remove the value or choose another one.

When I change an option on the first select, the value is changed in the workflow and the second select value is deleted. The only way to reinsert the value is by chaging it in the select , but I can't do that when there is only one value.

![image](https://github.com/bytechefhq/bytechef/assets/150443197/a3650b29-b4c7-4339-9bf3-d1c6d553bf62)
![image](https://github.com/bytechefhq/bytechef/assets/150443197/524cb2ca-b5da-4626-8779-0b82c61c800d)

### Steps To Reproduce

1. Copper component
2. Create company Action
3. create a company
4. Create activity Action
5. select Parent type: company
6. select the created in the Parent name combo box
7. change Parent type to something else
8. change parent type to company again

### Expected behavior

Either combo boxes should not be manually filled in with default values or the workflow should be automatically filled when combo box is filled.

### Version

latest

### OS

ubuntu

**Comment by kresimir-coko** [comment]
Github:
1. get issue Action ispuni ona 2 fielda
2. odi na create issue Action
3. ispuni 2 fielda
4. vrati se na get issue Action
5. probaj ispuniti issue
