### ISSUE TITLE
[bug]: an invalid connection is able to be chosen

### ISSUE THREAD

**Issue by marko-kriskovic** [bytechefhq/bytechef#1247]
### Describe the bug

when I try to make a connection and exit before a connection is made, I can see and select the connection in the UI

### Steps To Reproduce

1. Nifty Component
2. have http://localhost:5173/... in the URL
3. create a connection
4. exit after the infinite loading phase
5. try to use the connection

### Expected behavior

invalid and unfinished connections shouldn't show up in connections section

### Version

latest

### OS

ubuntu

**Comment by Tripathiaman2511** [comment]
I would like to work on this issue.

**Comment by marko-kriskovic** [comment]
I'm sorry, this was an error. It was actually not an issue

**Comment by Tripathiaman2511** [comment]
Oh Ok np
