### ISSUE TITLE
[bug]: components must be shown alphabetically

### ISSUE THREAD

**Issue by marko-kriskovic** [bytechefhq/bytechef#1255]
### Describe the bug

when I open a list of components, the first one is One Simple API, instead of Accelo
![image](https://github.com/user-attachments/assets/7b3a10d0-dac9-46ed-8dfa-fc760a130697)

### Steps To Reproduce

1.  create a project
2. open it
3. try to add a component

### Expected behavior

One Simple API should be under ODS File

### Version

latest

### OS

ubuntu

**Comment by F1nn-T** [comment]
Hey @marko-kriskovic, I would like to work on this as well. Should the sorting be on the frontend or backend?

**Comment by igorbeslic** [comment]
@F1nn-T
