### ISSUE TITLE
[bug]: UI says Actions instead of Triggers

### ISSUE THREAD

**Issue by marko-kriskovic** [bytechefhq/bytechef#1262]
### Describe the bug

when there are multiple triggers for the same component, the UI says Actions instead of Triggers
![image](https://github.com/user-attachments/assets/695fc2b1-feb9-4e45-b84e-6a9a6fbaedba)
![image](https://github.com/user-attachments/assets/109a9e2c-7c6a-4d4c-93e5-a6f08c267bd3)

### Steps To Reproduce

1. create a workflow
2. change the manual trigger to Pipdrive trigger

### Expected behavior

it should say "Triggers"

### Version

latest

### OS

ubuntu

**Comment by F1nn-T** [comment]
Hey, I would like to work on this issue, could you assign me?

**Comment by marko-kriskovic** [comment]
with pleasure :). Welcome to Bytechef
