### ISSUE TITLE
[bug] Action default property values are not set when changing the action in the ComponentDetails panel

### ISSUE THREAD

**Issue by ivicac** [bytechefhq/bytechef#1322]
Steps to reproduce:

1. Add HttpClient component
2. Open the ComponentDetails panel by clicking on the HttpClient component
3. Observer default parameters for GET action by opening the workflow code editor
4. Swith action to POST

EXPECTED
Default property values should be written under the `parameters` task property.

CURRENT
No written default property values are under the `parameters` task property.

https://share.cleanshot.com/K38XswVn

**Comment by kresimir-coko** [comment]
https://github.com/bytechefhq/bytechef/pull/1405
