### ISSUE TITLE
[feature] Allow choosing component actions in the component panel opening on the right side or in pop-up panal when clicking + button in the workflow editor

### ISSUE THREAD

**Issue by ivicac** [bytechefhq/bytechef#1397]
As a Workflow Developer
I want to be able to choose component actions in the component panel opening on the right side or in the pop-up panel when clicking the + button in the workflow editor
So that I don't need to select actions in the component details panel additionally

Context
We currently have two tabs in the abovementioned panels: Components and Triggers. That is inconsistent, as every task node in the workflow editor represents a component action, not the component itself.  The components tab should be renamed to the Actions tab, but the user must be able to choose a particular action in those panels

**Comment by kresimir-coko** [comment]
# Mockups

## Small scrollable modal/popup that offers a selection of actions
![image](https://github.com/user-attachments/assets/c6bbfb2b-2030-4020-a931-491ed44eb940)

## Vertically extended (collapsible) component card with a selection of actions
![image](https://github.com/user-attachments/assets/941caa07-9385-4381-a385-e2a72adc1014)

**Comment by ivicac** [comment]
@kresimir-coko ovo vrijedi i za izbor trigera

**Comment by kresimir-coko** [comment]
Final mockup (winner)

<img width="553" alt="image" src="https://github.com/user-attachments/assets/ce28ee63-fb19-471f-9a20-7b0af35fa216">
