### ISSUE TITLE
[docs]: How to use flow

### ISSUE THREAD

**Issue by khanhpd2002** [bytechefhq/bytechef#1463]
### Describe the problem

When I add a Flow like Condition in my Workflow, It always shows me this, and cant execute workflow anymore

![image](https://github.com/user-attachments/assets/24684c5f-ec09-49c9-8eb4-aa5e9cef92fd)

### Describe the improvement

Can you show me how to add Flow as a Workflow node into my workflow and then execute it.
Thanks for your support

**Comment by ivicac** [comment]
Hi @khanhpd2002, this still needs to be fully implemented in UI. Please track https://github.com/bytechefhq/bytechef/issues/1207.

Thx
