### ISSUE TITLE
[bug]: Options are not loaded

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1472]
### Describe the bug

Options are not loaded when component doesn't have connection

![image](https://github.com/user-attachments/assets/ce77abd9-3b48-408d-8a49-cba4774297d6)

### Steps To Reproduce

1. add date helper component with getCurrentDate action
2. at time zone property options are empty

### Expected behavior

/

### Version

latest

### OS

Ubuntu

**Comment by kresimir-coko** [comment]
https://github.com/bytechefhq/bytechef/pull/1482
