### ISSUE TITLE
[bug]: Add seconds to date time property

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1473]
### Describe the bug

Date time property should have seconds to add

![image](https://github.com/user-attachments/assets/2e659d0d-64a8-4301-9ec8-33e62dc1f8f7)

### Steps To Reproduce

1. add date helper component with date difference action

### Expected behavior

-

### Version

latest

### OS

Ubuntu

**Comment by kresimir-coko** [comment]
https://github.com/bytechefhq/bytechef/pull/1474
