### ISSUE TITLE
TextHelper - Markdown to HTML Action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1525]
Implement Markdown to HTMl action for Text Helper component.

The Markdown to HTML action converts Markdown content into HTML format,

Example: 

Markdown input:
```
  # Title

  This is a **paragraph** with a [link](https://example.com).

  - Item 1
  - Item 2
```

HTML ouput:
```
  <h1>Title</h1>
  <p>This is a <strong>paragraph</strong> with a <a href="https://example.com">link</a>.</p>
  <ul>
    <li>Item 1</li>
    <li>Item 2</li>
  </ul>
```

**Comment by rafabelts** [comment]
Hi, I would like to work in the issue!

**Comment by monikakuster** [comment]
Hey @rafabelts , welcome to Bytechef. :)

Please start with our [CONTRIBUTING.md](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md) guide.

[This part](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md#server-side) describes how to create new component or how to add new action or trigger to existing one.

[Here](https://docs.bytechef.io/developing_guide/components/connectors_manual/) is the detailed description of the structure of every component.

And finally, to test your action, [here](https://docs.bytechef.io/automation/getting-started/quick-start/) is the guide.

**Comment by rafabelts** [comment]
Hi @monikakuster , I'm still working on the action, been a bit busy lately, sorry for the delay.

**Comment by monikakuster** [comment]
@rafabelts any updates?
