### ISSUE TITLE
TextHelper - HTML to Markdown action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1526]
Implement HTML to Markdown action for Text Helper component.

The HTML to Markdown action converts HTML content into Markdown format.

Example: 
HTML Input:
```
  <h1>Title</h1>
  <p>This is a <strong>paragraph</strong> with a <a href="https://example.com">link</a>.</p>
  <ul>
    <li>Item 1</li>
    <li>Item 2</li>
  </ul>
```

Markdown output:
```
  # Title

  This is a **paragraph** with a [link](https://example.com).

  - Item 1
  - Item 2
```

**Comment by Brijeshthummar02** [comment]
hello there, @monikakuster i can work on this assign me the task also show me the complete path where to make file and all.

**Comment by monikakuster** [comment]
@Brijeshthummar02, please read our [CONTRIBUTING.md](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md), especially [this part](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md#server-side). 

New actions should be implemented inside [this](https://github.com/bytechefhq/bytechef/tree/master/server/libs/modules/components/text-helper/src/main/java/com/bytechef/component/text/helper/action) directory. Actions that are already implemented for the TextHelper component may be helpful.

**Comment by monikakuster** [comment]
Hey @Brijeshthummar02 .

[Here](https://github.com/bytechefhq/bytechef/blob/master/docs/src/content/docs/developing_guide/components/connectors_manual.md) is the detailed description of the structure of every component.

And finally, to test your action, [here](https://github.com/bytechefhq/bytechef/blob/master/docs/src/content/docs/automation/getting-started/quick-start.md) is the guide.

**Comment by monikakuster** [comment]
@Brijeshthummar02 any updates?
