### ISSUE TITLE
Google Contacts - Update Contact

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1528]
The Update Contact action for the Google Contacts component modifies an existing contact within user's Google Contacts account. 

**Action properties:**
- contact - resource name of the contact to be updated
- first name - updated first name of the contact
- middle name - updated middle name of the contact 
- last name - updated last name of the contact
- job title - updated job title associated with contact
- company - updated company name where the contact is employed
- email - updated email address of the contact
- phone number - updated phone number of the contact

**Ouput:**
- contact - the updated contact object, which includes all the modified details

Documentation Reference: https://developers.google.com/people/api/rest/v1/people/updateContact

**Comment by starrynighty** [comment]
Hello @monikakuster . I'm new to open source, and I'd love to contribute by tackling this issue. Can you assign it to me?

**Comment by monikakuster** [comment]
Hey @starrynighty , welcome to Bytechef. :)

Plese start with our [CONTRIBUTING.md](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md) guide.

[This part](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md#server-side) describes how to create new component or how to add new action or trigger to existing one.

[Here](https://docs.bytechef.io/developing_guide/components/connectors_manual/) is the detailed description of the structure of every component.

And finally, to test your action, [here](https://docs.bytechef.io/automation/getting-started/quick-start/) is the guide.
