### ISSUE TITLE
Copper - Create Task action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1530]
The Create Task action for the Copper component creates new task within the Copper CRM system. This action ensures that tasks are properly assigned, tracked, and managed.

**Action properties:**
- name - the name of the task
- assignee  - the ID of the user who will be responsible for completing the task
- due date - the date by which the task is expected to be completed
-  details - a detailed description of the task

**Ouput:**
-  task - the created task object

Documentation Reference: https://developer.copper.com/tasks/create-a-new-task.html

**Comment by vihar-s1** [comment]
@monikakuster  I would like to work on this issue along with some other components
