### ISSUE TITLE
Google Calendar - Update Event action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1531]
The Update Event action for the Google Calendar component is designed to modify an existing event within a user's Google Calendar.

**Action properties:**
- calendar ID - the ID of the calendar containing the event to be updated
- event ID - the ID of the event to be updated
- title - updated title of the event
- start time - updated start time of the event
- end time - updated end time of the event
- description - detailed description of the event
- attachments - files or documents associated with the event

**Ouput:**
-  event - the updated event object, which includes all the modified details

Documentation: https://developers.google.com/calendar/api/v3/reference/events/update

**Comment by swarupn17** [comment]
Hey @monikakuster I can do this task.
Please can you assign this task to me.
Thanks !

**Comment by monikakuster** [comment]
Hey, @swarupn17 any updates?
