### ISSUE TITLE
Google Drive - Delete File action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1533]
The Delete File action for the Google Drive component permanently deletes a specified file from the user's Google Drive. This action is a crucial feature for managing storage and maintaining an organized Google Drive.

**Action properties:**
- File ID - The ID of the file to be deleted

**Ouput:**
-  no output

Documentation Reference: https://developers.google.com/drive/api/reference/rest/v3/files/delete

**Comment by MayankMadan97** [comment]
Hey @monikakuster, can I work on this issue?

By the way, excellent job on the project's developer documentation. I was able to set up the entire project locally in no time.

**Comment by monikakuster** [comment]
> Hey @monikakuster, can I work on this issue?
> 
> By the way, excellent job on the project's developer documentation. I was able to set up the entire project locally in no time.
 
 Hey @MayankMadan97, welcome to Bytechef! :)
 
Thank you for the kind words about the documentation! I'm glad you managed to run the application on your own. 
Regarding the issue, please feel free to work on it. Let me know if you need any assistance or have questions as you proceed.

Since you've already run the application, i'm sure you've read our [CONTRIBUTING.md](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md) guide.

Here are some other helpuful instructions:

- [This part](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md#server-side) describes how to create new component or how to add a new action or trigger to an existing one.

- [Here](https://docs.bytechef.io/developing_guide/components/connectors_manual/) is the detailed description of the structure of every component.

- And finally, to test your action, [here](https://docs.bytechef.io/automation/getting-started/quick-start/) is the guide.

**Comment by MayankMadan97** [comment]
Thank you for the warm welcome! @monikakuster :)

I successfully implemented this action, but while testing, I’m wondering if there are any dummy or testing Google Drive credentials available. If not, I attempted to set up my own Google Drive API credentials, but I'm encountering a redirect URI mismatch error when trying to connect to the drive through the UI. I'm uncertain about which redirect URI to include when configuring the app (already tried http://127.0.0.1:5173/) in the Google Cloud Console. Could you provide some insights on this?

![image](https://github.com/user-attachments/assets/77ee402d-a7de-4c61-b018-ff33ea0da0a7)

**Comment by monikakuster** [comment]
You need to use your own API credentials. For the redirect URI, make sure to use `http://127.0.0.1:5173/callback`. You can find the application properties inside[ this file](https://github.com/bytechefhq/bytechef/blob/2819ded5505f82f07c9b5b7bacc5cea1edd09fb4/server/apps/server-app/src/main/resources/config/application.yml#L189).

**Comment by monikakuster** [comment]
> Thank you for the warm welcome! @monikakuster :)
> 
> I successfully implemented this action, but while testing, I’m wondering if there are any dummy or testing Google Drive credentials available. If not, I attempted to set up my own Google Drive API credentials, but I'm encountering a redirect URI mismatch error when trying to connect to the drive through the UI. I'm uncertain about which redirect URI to include when configuring the app (already tried http://127.0.0.1:5173/) in the Google Cloud Console. Could you provide some insights on this?
> 
> ![image](https://private-user-images.githubusercontent.com/41532876/374057964-77ee402d-a7de-4c61-b018-ff33ea0da0a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyODQ3NjgsIm5iZiI6MTcyODI4NDQ2OCwicGF0aCI6Ii80MTUzMjg3Ni8zNzQwNTc5NjQtNzdlZTQwMmQtYTdkZS00YzYxLWIwMTgtZmYzM2VhMGRhMGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA3MDEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0NDFiNDAxNDAzZDk5MDY0OWQxNDE1MmY4YzFhZDljNDVmZDljZjlkOGQ0OTNjMzFiYzExYjAzYzU4YzFlMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qJESLM-onEJ0OklfN6OiqyOPES3YEG1yK55ERF03JjM)

You need to use your own API credentials. For the redirect URI, make sure to use `http://127.0.0.1:5173/callback`. You can find the application properties inside[ this file](https://github.com/bytechefhq/bytechef/blob/2819ded5505f82f07c9b5b7bacc5cea1edd09fb4/server/apps/server-app/src/main/resources/config/application.yml#L189).

**Comment by MayankMadan97** [comment]
> > Thank you for the warm welcome! @monikakuster :)
> > I successfully implemented this action, but while testing, I’m wondering if there are any dummy or testing Google Drive credentials available. If not, I attempted to set up my own Google Drive API credentials, but I'm encountering a redirect URI mismatch error when trying to connect to the drive through the UI. I'm uncertain about which redirect URI to include when configuring the app (already tried http://127.0.0.1:5173/) in the Google Cloud Console. Could you provide some insights on this?
> > ![image](https://private-user-images.githubusercontent.com/41532876/374057964-77ee402d-a7de-4c61-b018-ff33ea0da0a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyODQ3NjgsIm5iZiI6MTcyODI4NDQ2OCwicGF0aCI6Ii80MTUzMjg3Ni8zNzQwNTc5NjQtNzdlZTQwMmQtYTdkZS00YzYxLWIwMTgtZmYzM2VhMGRhMGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA3MDEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0NDFiNDAxNDAzZDk5MDY0OWQxNDE1MmY4YzFhZDljNDVmZDljZjlkOGQ0OTNjMzFiYzExYjAzYzU4YzFlMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qJESLM-onEJ0OklfN6OiqyOPES3YEG1yK55ERF03JjM)
> 
> You need to use your own API credentials. For the redirect URI, make sure to use `http://127.0.0.1:5173/callback`. You can find the application properties inside[ this file](https://github.com/bytechefhq/bytechef/blob/2819ded5505f82f07c9b5b7bacc5cea1edd09fb4/server/apps/server-app/src/main/resources/config/application.yml#L189).

Thanks @monikakuster for your help! I have raised the PR for this issue.
