### ISSUE TITLE
Google Drive - Copy File action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1534]
The Copy File action for the Google Drive component is designed to duplicate a specified file within the user's Google Drive. This action ensures that files can be easily copied to different locations or renamed as needed.

**Action properties:**
- file ID - the ID of the file to be copied
- file name - name of the new file created as a result of the copy operation
- folder ID - the ID of the folder where the copied file will be stored

**Ouput:**
-  file - the newly created file object

Documentation Reference: https://developers.google.com/drive/api/reference/rest/v3/files/copy

**Comment by MayankMadan97** [comment]
Hey @monikakuster, can you assign this issue to me?
