### ISSUE TITLE
Gmail - Delete Email action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1535]
The Delete Email action for the Gmail component moves an email message to the trash. This action ensures that the specified email is no longer visible in the user's inbox or other folders.

**Action properties:**
- Message ID - The ID of the email message to be deleted

**Ouput:**
-  no output

Documentation: https://developers.google.com/gmail/api/reference/rest/v1/users.messages/delete

**Comment by nodtem66** [comment]
Hello @monikakuster 
I'll take care of this.

**Comment by monikakuster** [comment]
Hey @nodtem66, welcome to Bytechef. :)

Plese start with our [CONTRIBUTING.md](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md) guide.

[This part](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md#server-side) describes how to create new component or how to add new action or trigger to existing one.

[Here](https://docs.bytechef.io/developing_guide/components/connectors_manual/) is the detailed description of the structure of every component.

And finally, to test your action, [here](https://docs.bytechef.io/automation/getting-started/quick-start/) is the guide.
