### ISSUE TITLE
Implement Add Key-Value Pairs for Object Helper

### ISSUE THREAD

**Issue by marko-kriskovic** [bytechefhq/bytechef#1539]
Given the initial object (map or array), the user would define an array of key-value pairs. Those pairs need to then be added onto the object (if they don't exist). Returns the modified object

**Comment by nodtem66** [comment]
@marko-kriskovic 
I'll take care of this.

## Examples:

### Example1
**Inputs:**
Initial object: 
```json
{ "key1": "value1", "key2": "value2" }
```
List of key-value pairs:
```json
[["key3", "value3"], ["key4", "value4"]]
```

**Output:**
```json
{ "key1": true, "key2": "value2", "key3": "value3", "key4": "value4"}
```

---

### Example2
**Inputs:**
Initial object:
```json
{ "key1": "value1", "key2": "value2" }
```
List of key-value pairs: 
```json
[["key1", "value3"], ["key2", "value4"]]
```

**Output:**
```json
{ "key1": "value3", "key2": "value4" }
```
