### ISSUE TITLE
Implement Delete Key-Value Pair for Object Helper

### ISSUE THREAD

**Issue by marko-kriskovic** [bytechefhq/bytechef#1541]
Action: Delete Key-Value Pair

Description: deletes a key-value pair in the given object by the specified key. Returns the modified object

Input Types: object(INPUT), string(KEY)
Output Types: object()

Inputs: 
`input: {
key1: value1,
key2: value2
}`
`key: "key1"`

Output:
`input:{
key2: value2,
}`

**Comment by xStuti12** [comment]
Hello @marko-kriskovic  I´m a student and I would like to resolve this issue for you, can you assign it to me?

**Comment by marko-kriskovic** [comment]
Hey @xStuti12, welcome to Bytechef! :smile: 

Please start with out [Contributing](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md) guide.

[Here](https://docs.bytechef.io/developing_guide/components/connectors_manual/)  is the link to the recently published documentation.

**Comment by xStuti12** [comment]
Hello again @marko-kriskovic I implemented a solution for this issue and have also created a pull request. However I have not been able to generate the documentation for my implementation due to an unknown error. Please check the implementation and notify me of any discrepancies :)
