### ISSUE TITLE
Implement Merge Two Objects for Object Helper

### ISSUE THREAD

**Issue by marko-kriskovic** [bytechefhq/bytechef#1542]
Action: Merge Two Objects 

Description: merges two given objects. The first object always has priority. For example: if they have different values, but same key, the first object's value is going to be in the returned object. Returns the modified object

Input Types: object(INPUT), object(INPUT2)
Output Types: object()

Inputs: 
`input: {
key1: value1,
key2: value2
}`
`input2: {
key1: newValue,
key3: value3
}`

Output:
`input:{
key1: value1,
key2: value2,
key3: value3
}`

**Comment by Shripad-Joshi** [comment]
Hello @marko-kriskovic, I would like to work on this issue.
