### ISSUE TITLE
Monday - Create Board action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1548]
The Create Board action for the Monday component creates new board within the Monday.com platform.

**Action properties:**
- board kind - type of board to create, possible types: private, public, share
- board name - name of the new board
- description - detailed description of the new board

**Ouput:**
-  board - the newly created board object

Documentation Reference: https://developer.monday.com/api-reference/reference/boards#create-a-board

**Comment by kalai4eng** [comment]
Can work on this as well..please assign !
