### ISSUE TITLE
Monday - Delete Item action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1549]
The Delete Item action for the Monday component deletes an item from a board within the Monday.com platform.

**Action properties:**
- item ID - ID of the item to be deleted

**Ouput:**
-  no output

Documentation Reference: https://developer.monday.com/api-reference/reference/items#delete-an-item

**Comment by kalai4eng** [comment]
I can work on this ! Please assign @monikakuster !
