### ISSUE TITLE
Jira - Add Issue Comment action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1551]
The Add Issue Comment action fot the Jira component adds a comment directly to an issue within a Jira project.

**Action properties:**
- project ID - ID of the project where the issue is located
- issue ID - ID of the issue to which the comment will be added
- comment - the text of the comment to be added to the issue

**Ouput:**
-  comment - the newly created comment object

Documentation Reference: https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issue-comments/#api-rest-api-3-issue-issueidorkey-comment-post

**Comment by vihar-s1** [comment]
@monikakuster  I would like to work on this issue along with some other components
