### ISSUE TITLE
ImageHelper - Get Image Metadata action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1553]
The Get Image Metadata action for the Image Helper component is designed to extract and provide detailed metadata from an image file. This action is essential for applications that require information about image properties, such as dimensions, format, color depth, and more.

**Action Properties:**
- image file - the image file from which metadata will be extracted

**Output:**
- metadata - a structured object containing various metadata attributes of the image

**Comment by Shripad-Joshi** [comment]
Hello @monikakuster , I would like to work on this issue.

**Comment by monikakuster** [comment]
Hey @Shripad-Joshi , welcome to Bytechef. :)

Plese start with our [CONTRIBUTING.md](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md) guide. [This part](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md#server-side) describes how to create new component or how to add new action or trigger to existing one.

[Here](https://docs.bytechef.io/developing_guide/components/connectors_manual/) is the detailed description of the structure of every component.

And finally, to test your action, [here](https://docs.bytechef.io/automation/getting-started/quick-start/) is the guide.

**Comment by Shripad-Joshi** [comment]
Hello @monikakuster, Contributing.md guide is stating to create issue branch from develop branch, but I am not able find develop branch.

![image](https://github.com/user-attachments/assets/f68ef6db-903f-4deb-b598-2fb804e9d09d)

Can you please help me?

**Comment by monikakuster** [comment]
@Shripad-Joshi sorry for the confusion; it was our mistake. We accidentally deleted the develop branch, but it has now been restored. You can go ahead and create your issue branch from the develop branch.

**Comment by Shripad-Joshi** [comment]
Hello @monikakuster , small doubt about output you want it in structured object, then can I create a class in constant package to store and return image metadata.

**Comment by monikakuster** [comment]
Hey, @Shripad-Joshi...

Yes, go ahead and create it in the way you think is best. I will review the pull request and determine if any refactoring is needed.
