### ISSUE TITLE
ImageHelper - Crop Image action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1554]
The Crop Image action for the Image Helper component is designed to allow users to trim or cut out a specific portion of an image, focusing on the area of interest while removing unwanted sections. This action is essential for applications that require precise image editing and manipulation.

**Action Properties:**
- image file - the image file to be cropped
- x coordinate - the horizontal starting point of the crop area
- y coordinate - the vertical starting point of the crop area
- width - width of the crop area
- height - height of the crop area
- result file name - specifies the output file name for the result image

**Output:**
- cropped image - resulting image object after the crop operation

**Comment by holyjacobes** [comment]
Hey @monikakuster, if still open, I would love to contribute by solving this issue.

**Comment by monikakuster** [comment]
Hey @holyjacobes  , welcome to Bytechef. :)

Plese start with our [CONTRIBUTING.md](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md) guide. [This part](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md#server-side) describes how to create new component or how to add new action or trigger to existing one.

[Here](https://docs.bytechef.io/developing_guide/components/connectors_manual/) is the detailed description of the structure of every component.

And finally, to test your action, [here](https://docs.bytechef.io/automation/getting-started/quick-start/) is the guide.

**Comment by holyjacobes** [comment]
Hey @monikakuster, 

I implemented crop image action, please check it out if everything is OK :)
