### ISSUE TITLE
Nutshell - Create Company action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1561]
The Create Company action for the Nutshell component adds a new company record to a user's Nutshell CRM account.

**Action properties:**
- name - the name of the new company
- description - detailed description of the new company
- email - email address associated with the company
- phone - phone number associated with the company

**Ouput:**
-  company - the newly created company object

Documentation Reference: https://developers.nutshell.com/reference/post_accounts

**Comment by kalai4eng** [comment]
Hello @monikakuster ! I would like to work on this issue

**Comment by kalai4eng** [comment]
PR raised !

https://github.com/bytechefhq/bytechef/pull/1591

Please take a look and let me know for any feedbacks :)
