### ISSUE TITLE
Nutshell - Create Lead action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1562]
The Create Lead action for the Nutshell component  adds a new lead record to a user's Nutshell CRM account.

**Action properties:**
- description - description of the lead, which is also set as the name of the lead
- assignee - The ID of the user the lead is assigned to

**Ouput:**
- lead - the newly created lead object

Documentation Reference: https://developers.nutshell.com/reference/post_leads-2

**Comment by Sanketpatil27** [comment]
can you please describe the issue, that is what should be done?

**Comment by monikakuster** [comment]
Hey @Sanketpatil27. I updated the desctription for the issue.

If you are new to Bytechef, please read our [CONTRIBUTING.md(https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md)

[This part](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md#server-side) describes how to create new component or how to add new action or trigger to existing one.

[Here](https://github.com/bytechefhq/bytechef/blob/master/docs/src/content/docs/developing_guide/components/connectors_manual.md) is the detailed description of the structure of every component.

And finally, to test your action, [here](https://github.com/bytechefhq/bytechef/blob/master/docs/src/content/docs/automation/getting-started/quick-start.md) is the guide.

**Comment by monikakuster** [comment]
@Sanketpatil27, would you like to work on this issue?

**Comment by kalai4eng** [comment]
Hello @monikakuster ! I would like to work on this issue

**Comment by monikakuster** [comment]
Hey, @kalai4eng welcome to Bytechef :)

**Comment by kalai4eng** [comment]
Hey  @monikakuster ! quick query !

In issue its mentioned as https://developers.nutshell.com/reference/post_accounts for reference API ! 
Is this a typo instead of https://developers.nutshell.com/reference/post_leads-2 to create Lead ?  

If yes , as per documentation they don't have support to add name & assignee directly.

i) For name => **description** (Which will be considered as name & description)
ii) For Assignee => Should i go ahead and add as custom field , assuming the customer will create that custom field ? 

Or Am is missing something here ! please guide on the same . Thanks

**Comment by monikakuster** [comment]
> Hey @monikakuster ! quick query !
> 
> In issue its mentioned as https://developers.nutshell.com/reference/post_accounts for reference API ! Is this a typo instead of https://developers.nutshell.com/reference/post_leads-2 to create Lead ?
> 
> If yes , as per documentation they don't have support to add name & assignee directly.
> 
> i) For name => **description** (Which will be considered as name & description) ii) For Assignee => Should i go ahead and add as custom field , assuming the customer will create that custom field ?
> 
> Or Am is missing something here ! please guide on the same . Thanks

Whoops, sorry about that. I've updated the issue description.
Regarding your question, the `assignee` is actually `owner` within the `links` object.

**Comment by kalai4eng** [comment]
Hey @monikakuster  ! quick query 

For Assignee/Owner: Which option best suits in our use case

**Direct User Input (Pass assigneeId):**
Allow the user to directly to pass the assigneeId . 

**User Selection from a List:**
Present a list of users from which they can select an assignee

**Comment by monikakuster** [comment]
@kalai4eng, I recommend going with the second option. This approach ensures that users can only select from a predefined list of valid users.
