### ISSUE TITLE
[bug]: Monaco Editor used inside WorkflowEditor lost the fold/unfold functionality

### ISSUE THREAD

**Issue by kresimir-coko** [bytechefhq/bytechef#1565]
### Describe the bug

We lost the ability to fold/unfold code inside the MonacoEditor used when manually editing the workflow in JSON.

### Steps To Reproduce

1. Create a workflow and add some component actions to it
2. Click on the `</ >` icon in the right sidebar
3. Notice there are no fold/unfold icons next to the line numbers like in VSC (or other IDEs)

![image](https://github.com/user-attachments/assets/9013c21d-350f-454c-8018-009b27f8629b)

### Expected behavior

There should be little carets allowing you to fold/unfold blocks of code like in native code editors

**Comment by Aakarshit07** [comment]
@kresimir-coko 
can you describe the issue ?

**Comment by kresimir-coko** [comment]
@Aakarshit07 I've updated the description and assigned the ticket to you. Let me know if you need anything else ❤️

**Comment by Aakarshit07** [comment]
Thank you, I'll start working on it.

**Comment by kresimir-coko** [comment]
@Aakarshit07 any updates?

**Comment by Aakarshit07** [comment]
@kresimir-coko Hey, sorry for the delay.
I’m mostly done with the bug, but I got a bit busy with the festivals here.
I should be able to raise the PR within the next 2 to 3 days.

**Comment by Aakarshit07** [comment]
Thank you for allows me to work on this.
I have raised an PR: 
https://github.com/bytechefhq/bytechef/pull/1692
