### ISSUE TITLE
Github - Add Assignees to Issue action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1567]
The Add Assignes to an Issue  action for the Github component assigns multiple users to a specific issue within a Github repository.

**Action properties:**
- repository - repository where the issue is located
- issue - the issue to which assignees will be added
- assignees - list up to 10 assignees to be added to the issue

**Ouput:**
- issue - updated issue object

Documentation Reference: https://docs.github.com/en/rest/issues/assignees?apiVersion=2022-11-28#add-assignees-to-an-issue

**Comment by MayankMadan97** [comment]
Hey @monikakuster, I can take this up. Please assign me this issue. Thanks.

**Comment by MayankMadan97** [comment]
Hey @monikakuster, I’m working on the input property for assignees (up to 10), and I’m wondering what property type would work best. Should we go with an ARRAY_BUILDER to let users configure any username, or should we limit it to collaborators/contributors and use MULTI_SELECT options instead? I’d love to hear your thoughts!

**Comment by monikakuster** [comment]
Hi, @MayankMadan97 for the input property for assignees, I recommend going with the second option. This approach ensures that users can only select from a predefined list of valid usernames. By restricting the selection to known collaborators/ contributors, you also streamline the user experience, making it easier and faster for users to assign tasks without having to manually input each username.

**Comment by monikakuster** [comment]
@MayankMadan97 Since you will have options on the array item, they won't be loaded in the UI. We have an open [issue](https://github.com/bytechefhq/bytechef/issues/1575) for that. Nevertheless, you can go ahead and send a PR.

**Comment by monikakuster** [comment]
Yeah, that sounds good. We can proceed with that approach. I will notify you when this bug is fixed so you can update the action. :)

**Comment by MayankMadan97** [comment]
@monikakuster, Sounds good! Just wanted to let you know that I've submitted a PR for this.
