### ISSUE TITLE
Github - Add Labels to Issue action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1568]
The Add Labels to an Issue action for the Github component adds labels to a specific issue within a Github repository.

**Action properties:**
- repository - repository where the issue is located
- issue - the issue to which labels will be added
- labels - list of labels to be added to the issue

**Ouput:**
- issue - updated issue object

Documentation Reference: https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#add-labels-to-an-issue

**Comment by MayankMadan97** [comment]
Hey @monikakuster, I can take this up. Please assign me this issue. Thanks.
