### ISSUE TITLE
Nifty - Create Project action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1576]
The Create Project action for the NIfty component creates a new project within the Nifty project management platform.

**Action properties:**
- name - the name of the project
- description - summary of the project's purpose, goals, or any other relevant information that provides context for team members
- template id - ID for a project template that can be used to pre-configure the project

**Ouput:**
- project - the newly created project object

Documentation Reference: https://developers.niftypm.com/operation/operation-projectapicontroller_createproject

**Comment by MayankMadan97** [comment]
Hey @monikakuster, I can work on this issue.

**Comment by MayankMadan97** [comment]
Hi @monikakuster, unfortunately, I’m unable to work on these items at the moment. I’m unassigning myself so someone else can take it over.
