### ISSUE TITLE
Figma - Get File Comments action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1598]
Implement the Get File Comments action for the Figma component to retrieve all comments associated with a specific file in Figma. This action allows users to access feedback and discussions directly from the design file, facilitating collaboration and review processes.

**Action properties:**
- file key - key for the Figma file from which you want to retrieve comments

**Ouput:**
- comments - A collection of comments that have been left on the specified file

Documentation Reference: https://www.figma.com/developers/api#get-comments-endpoint

**Comment by Shripad-Joshi** [comment]
Hello @monikakuster , I would like to work on this issue.

**Comment by monikakuster** [comment]
@Shripad-Joshi any updates?
