### ISSUE TITLE
Google Forms - Get Response action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1613]
Implement the Get Response action for the Google Forms component to efficiently retrieve a specific response submitted for a particular form. 

**Action properties:**
- form id - id of the form from which you want to retrieve responses
- response id - id of the specific response you wish to retrieve

**Ouput:**
- response - a response object containing detailed information about the submission

Documentation Reference: https://developers.google.com/forms/api/reference/rest/v1/forms.responses/get

**Comment by vihar-s1** [comment]
Hello! I would like to work on this issue. I have some experience working with workflows from my current employment so I think I would be good fit for this issue.

**Comment by monikakuster** [comment]
Hey @vihar-s1 , welcome to Bytechef. :)

Plese start with our [CONTRIBUTING.md](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md) guide. [This part](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md#server-side) describes how to create new component or how to add new action or trigger to existing one.

[Here](https://docs.bytechef.io/developing_guide/components/connectors_manual/) is the detailed description of the structure of every component.

And finally, to test your action, [here](https://docs.bytechef.io/automation/getting-started/quick-start/) is the guide.

**Comment by vihar-s1** [comment]
Thanks for assigning me. Nice to see such a great new contributors setup 😃

**Comment by vihar-s1** [comment]
I went through the existing google Forms action and some of the google drive actions to get some overview of things and will be starting the implementation now. I just want to clarify if you want just the **get single response** action, or do you also want a **get all responses** action as well?

<img width="601" alt="Screenshot 2024-10-17 at 11 35 04 PM" src="https://github.com/user-attachments/assets/d8c731ee-a662-462a-bfb5-4c1577c1f374">

one last thing. Should I be adding myself as an author using the `@author` annotation over the action classes ?

**Comment by monikakuster** [comment]
Both actions need to be implemented to enhance the functionality of our Google Forms integration. There is an open issue for each action: this issue pertains to the `Get Single Response `action, which retrieves a specific response from a form based on its unique identifier. Issue #1612 covers the `Get All Responses` action, which fetches all responses submitted to a form.

Yes, please add yourself as the author using the @author annotation over the action classes. This helps maintain clear documentation of contributions and ensures that credit is appropriately attributed to those who develop specific components of the project.

**Comment by vihar-s1** [comment]
Got it! Thanks. Will be raising a PR for get single response soon

**Comment by vihar-s1** [comment]
I am trying to run `gradle spotlessApply` but constantly encountering this error.
can you guide as to how can I resolve this error


```bash
Starting a Gradle Daemon (subsequent builds will be faster)
Kotlin does not yet support 22 JDK target, falling back to Kotlin JVM_21 JVM target

> Task :buildSrc:compileKotlin FROM-CACHE
Kotlin does not yet support 22 JDK target, falling back to Kotlin JVM_21 JVM target

FAILURE: Build failed with an exception.

* Where:
Build file '/*****/*****/*****/*****/bytechef/build.gradle.kts' line: 1

* What went wrong:
An exception occurred applying plugin request [id: 'jacoco-report-aggregation']
> Failed to apply plugin 'org.gradle.jacoco-report-aggregation'.
   > Cannot query the value of this provider because it has no value available.
     The value of this provider is derived from:
       - property 'testType'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.9/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 11s
10 actionable tasks: 4 executed, 6 from cache
```

**Comment by vihar-s1** [comment]
@monikakuster 

had some doubts regarding my PR. Posting again here since I didn't got any reply on the conversation in the PR.

- Do you want a longer commit message or a commit description ? I do prefer adding description but usually people focus more on the PR details and PR name rather than commit that is why I stopped adding description by default.

- I have a doubt though. I didn't understand what you meant by "Google Forms component is not implemented using the Google Java SDK" I am using google API services only for getting the response and the Form compnent is also from the google API sdk so I didn't understood what your expectation is with respect to the getResponseOptions method.
