### ISSUE TITLE
Baserow - Get Row action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1643]
Implement the Get Row action for the Baserow component to allow users to retrieve specific rows from a table within their Baserow database. 

**Action properties:**
- table id - id of the table from which you want to retrieve the row 
- row id - id of the row you wish to retrieve

**Ouput:**
- row - the row object containing all the data fields and values associated with the specified row

Documentation Reference: https://baserow.io/api-docs

**Comment by monikakuster** [comment]
Hey @arilloid, welcome to Bytechef. :)

Plese start with our [CONTRIBUTING.md](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md) guide. [This part](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md#server-side) describes how to create new component or how to add new action or trigger to existing one.

[Here](https://docs.bytechef.io/developing_guide/components/connectors_manual/) is the detailed description of the structure of every component.

And finally, to test your action, [here](https://docs.bytechef.io/automation/getting-started/quick-start/) is the guide.

**Comment by arilloid** [comment]
Hello @monikakuster , 

I apologize for any inconvenience caused, but I realized I’m unable to complete this issue.
I’ll go ahead and unassign myself so someone else can take it on.
