### ISSUE TITLE
Google Drive - Get File action

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1647]
The Get File action for the Google Drive component is designed to retrieve a specified file from the user's Google Drive. This action allows users to access file metadata and content.

**Action properties:**
- file ID - the ID of the file you wish to retrieve

**Ouput:**
-  file - a file object containing detailed information about the retrieved file. 

Documentation Reference: https://developers.google.com/drive/api/reference/rest/v3/files/get

**Comment by Shivakarthikeya23** [comment]
I can work on it. Can you please assign it to me ?

**Comment by monikakuster** [comment]
Hey @Shivakarthikeya23, welcome to Bytechef. :)

Plese start with our [CONTRIBUTING.md](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md) guide. [This part](https://github.com/bytechefhq/bytechef/blob/master/CONTRIBUTING.md#server-side) describes how to create new component or how to add new action or trigger to existing one.

[Here](https://docs.bytechef.io/developing_guide/components/connectors_manual/) is the detailed description of the structure of every component.

And finally, to test your action, [here](https://docs.bytechef.io/automation/getting-started/quick-start/) is the guide.

**Comment by arilloid** [comment]
Hi @monikakuster,

I would like to work on this issue

I was very happy to see my PR for #1642 get merged, thank you for reviewing it! Do you have any feedback on how I can further improve my contributions?

I also wanted to ask about the documentation,  I ran `gradlew generateDocumentation` from the Baserow module, but it didn’t seem to generate any docs. Would you happen to have any pointers on what might be causing this (should I try running `generateDocumentation` from the root of the project instead)?
