### ISSUE TITLE
[bug]: Internal Server Error when changing the port

### ISSUE THREAD

**Issue by akala444** [bytechefhq/bytechef#1650]
### Describe the bug

When I changed the port from 8080 to 5173 in docker.compose.yml and enter any component I got the Internal Server Error shown in image below.
<img width="1437" alt="bug1" src="https://github.com/user-attachments/assets/185343b1-6d50-4c88-9929-0751fc46ed10">

### Steps To Reproduce

1. Go to docker.compose.yml in /bytechef/docker.compose.yml
2. Change port number on line 32, from - "8080:8080" to - "5173:8080"
3. Log in to Bytechef
4. Open any workflow and go into any component
5. Also, when entering Connections, loading is forever

### Expected behavior

I expect components to work without any errror as it was with previous port 8080.

### Version

Latest

### OS

macOS 14.6.1

### Browser

Google Chrome

**Comment by ivicac** [comment]
Improved exception handčing to show proper message, as it is related to the wrong encryption key
