### ISSUE TITLE
Extract all absolute values into variables

### ISSUE THREAD

**Issue by kresimir-coko** [bytechefhq/bytechef#1661]
In places where we use a absolute color (`bg-[#FFF]`) or dimensions (`w-[500px]`), extract those into variables inside `tailwind.config.js`.

Bonus points (but not necessary for this ticket) for an ESLint rule to enforce this change so we automate the check and ensure we don't introduce new absolute values.

**Comment by monikakuster** [comment]
Hey @Rinakat225, welcome to Bytechef! :smile:

**Comment by Aakarshit07** [comment]
@kresimir-coko hey anyone working on this issue ?
