### ISSUE TITLE
[bug] When changing action in WorkflowNodeDetailsPanel, the panel is flickering

### ISSUE THREAD

**Issue by ivicac** [bytechefhq/bytechef#1682]
https://share.cleanshot.com/51gbQdly

**Comment by kresimir-coko** [comment]
Fixed in https://github.com/bytechefhq/bytechef/issues/1628

**Comment by kresimir-coko** [comment]
Sorry @MadhurSaluja but tickets that weren't marked with the hacktoberfest tag weren't for public,
