### ISSUE TITLE
[bug]: Unable to create instance

### ISSUE THREAD

**Issue by igorbeslic** [bytechefhq/bytechef#1746]
### Describe the bug

When I click create instance button pop-up panel does not contain existing Projects in drop down list.

### Steps To Reproduce

Go to Instances View
Click New Instance
Expected:
Projects drop down contains projects
Actually
Panel is completely empty - no any Project in the list

### Expected behavior

I expect Projects

OR if anything else is wrong I would expect that UI says to me... Like "You have projects but no workflow in them." Or something else.

### Version

aws_stable

### OS

Ubuntu 24.04 LTS

### Browser

Chrome

**Comment by igorbeslic** [comment]
It is not obvious that project should be published.

Conclusion:
Only published project can be used to make an instance. That fact could be visible in Instance UI, or in Instance creation Panel.
@ivicac and @akala444 I would like to create an UX improvement request. Do you think it is worth? Also if we already have UX improvement ticket for Instances please direct me to the ticket.
Thank you!!!

**Comment by ivicac** [comment]
For now, an additional message that says there are no published projects yet. If that is not enough then @akala444 can suggest additional improvement
