### ISSUE TITLE
[bug]: Additional properties are not loaded properly

### ISSUE THREAD

**Issue by monikakuster** [bytechefhq/bytechef#1751]
### Describe the bug

The additionalProperties method fails to load the defined properties. Expected behavior is that all specified properties should be loaded correctly, but currently, they are not.

### Steps To Reproduce

1. add open ai componetn with ask action
2.  for response format property select object
3. click add object property

![image](https://github.com/user-attachments/assets/09324a44-bc9c-4965-9fab-88288cfea9d2)

### Expected behavior

Under type should be 5 custom objects with labels : Integer, String, Boolean, Number and Date

### Version

latest

### OS

Ubuntu

**Comment by ivicac** [comment]
Not reproducible anymore

**Comment by monikakuster** [comment]
Not reproducible anymore
