### ISSUE TITLE
[bug]: display condition not showing for connection properties

### ISSUE THREAD

**Issue by marko-kriskovic** [bytechefhq/bytechef#1752]
### Describe the bug

when I try to make a connection, every property that has displayCondition isn't showing

### Steps To Reproduce

1. branch 1744
2. component AI TextAnalysis
3. open connections
4. change Authorization to "Other (Bearer Token)"
5. select a connection provider (preferably to something that's not Amazon Bedrock)

### Expected behavior

I should be able to use displayCondition for connection properties

### Version

latest

### OS

ubuntu

**Comment by ivicac** [comment]
Not reproducible anymore
