### ISSUE TITLE
[feature] Switching Trigger type in the Workflow editor

### ISSUE THREAD

**Issue by ivicac** [bytechefhq/bytechef#372]
As a Workflow Developer
I want to choose different types of triggers
So that I can trigger workflows in different ways. 

Acceptance Criteria
TODO

Tasks
- [x] Move Actions/Triggers/Flows side panel on the right side, check https://assets.website-files.com/5de921a1902d8d39a699f77e/64872d76385108bf583c0cf7_Screenshot-2023-04-27-at-10.28.27.png
- [x] Side panel and pop-up in workflow editor - add tabs for triggers/actions/flows
- [ ] Make WorkflowNodeDetailsPanel works with triggers

Balsmiq: https://balsamiq.cloud/spslzug/ph7qmda/r7391

**Comment by kresimir-coko** [comment]
https://github.com/bytechefhq/bytechef/pull/902
