### ISSUE TITLE
[workflow]: Pull data from CSV file and insert to database table - files

### ISSUE THREAD

**Issue by ivicac** [bytechefhq/bytechef#556]
Workflow steps:

1. Email Trigger
2. Create/download a CSV file from URL
3. Use the created file by iterating through each line
4. Insert each line to a database table

Sample csv file: https://people.sc.fsu.edu/~jburkardt/data/csv/cities.csv.

### Note:
It is not the goal to replicate the steps but to get awareness of what the workflow does and try to get the same results by applying the atlas engine and tasks developed and adjusted to it.

**Comment by igorbeslic** [comment]
implemented:
https://github.com/bytechefhq/bytechef-workflows/blob/master/projects/samples/basic_workflows/read_csv_and_insert_into_db.json
