### ISSUE TITLE
[bug]: HttpClient Component - Query Parameters, Header Parameters - value type is Array but UI renders Text input

### ISSUE THREAD

**Issue by igorbeslic** [bytechefhq/bytechef#900]
### Describe the bug

UI for HttpClient should provide User with Array Item Editor to define Headers and Query Parameters values. By HTTP specification both, headers and query parameter values can accept multiple values.

JSON format of queryParameters in workflow definition in CodeEditor should be:

```typescript
{
    "label": "New Workflow",
    "description": "",
    "inputs": [],
    "triggers": [],
    "tasks": [
        {
            "label": "HTTP Client",
            "name": "httpClient_1",
            "type": "httpClient/v1/get",
            "parameters": {
                "uri": "o/tecajn/v1",
                "responseType": "JSON",
                "queryParameters": {
                    "datum": [
                        "2014-01-02"
                    ]
                },
                "fullResponse": "true",
                "ignoreResponseCode": "false"
            }
        },
        {
            "label": "Logger",
            "name": "logger_1",
            "type": "logger/v1/debug",
            "parameters": {
                "text": "Result is ${httpClient_1.body}"
            }
        }
    ]
}
``` 

### Steps To Reproduce

- Add HttpClient to the arbitrary workflow
- Click Properties tab

### Expected behavior

`given` HttpClient Connection
`and` base URL `https://api.hnb.hr/`
`and` Authorization set to `None`
`when` user creates workflow
`and` **HttpClient** is selected
`and` **Properties tab** is selected
`and` in section **Query parameters** button **Add property** is clicked
`and` _Add Property dialog_ is shown
`and` **Name** is set to `datum`
`and` property type is Array
`then` UI should provide way to define Array items

### Version

2.3.1

### OS

MacOsX

### Browser

Chrome

### Additional context

context

**Comment by kresimir-coko** [comment]
https://github.com/bytechefhq/bytechef/pull/978
