### ISSUE TITLE
[bug]: when adding the root datapill to MentionsInput, it doesn't save as a datapill in definition, but as a regular string

### ISSUE THREAD

**Issue by marko-kriskovic** [bytechefhq/bytechef#918]
### Describe the bug

When I click on a output from a trigger, workflow code editor doesn't automatically turn it into code. 

![Screenshot from 2024-04-24 16-18-52](https://github.com/bytechefhq/bytechef/assets/150443197/4e2ce7a5-1870-4bdc-892e-d1387b1f19d6)
![Screenshot from 2024-04-24 16-19-05](https://github.com/bytechefhq/bytechef/assets/150443197/08e075d8-c3f2-4664-9bf8-5bb5422c6c2f)

### Steps To Reproduce

1. make a trigger
2. make another connector
3. click on output on data pill panel

### Expected behavior

it should be in ${googleSheets_1} format

### Version

latest

### OS

ubuntu

**Comment by kresimir-coko** [comment]
https://github.com/bytechefhq/bytechef/pull/978
