### ISSUE TITLE
[bug]: As User I expect duplicate workflow would suffix workflow name  

### ISSUE THREAD

**Issue by igorbeslic** [bytechefhq/bytechef#937]
### Describe the bug

As User I expect duplicate workflow would suffix workflow name with number or anything else to make clear distinction of original and its copy.
In this moment where UI does not refresh properly, only way to distinct original from copy is create date.

### Steps To Reproduce

duplicate

### Expected behavior

duplicate creates Original Name - Timestamp

### Version

2.3.1

### OS

MacOsX

### Browser

Chrome

**Comment by ivicac** [comment]
Zatvaram...
