### ISSUE TITLE
[bug]: close data pill panel when closing component window

### ISSUE THREAD

**Issue by marko-kriskovic** [bytechefhq/bytechef#954]
### Describe the bug

When I close a component, the data pill panel isn't closing
![Screenshot from 2024-04-30 13-27-46](https://github.com/bytechefhq/bytechef/assets/150443197/8088b9dc-bdd1-4729-9111-982f2b628551)

### Steps To Reproduce

1. create a component
2. go to properties
3. click on input supporting data pills
4. close the window

### Expected behavior

everything should close when the component is closed

### Version

latest

### OS

ubuntu

**Comment by kresimir-coko** [comment]
https://github.com/bytechefhq/bytechef/pull/961
