### ISSUE TITLE
[bug]: changing the action doesn't work

### ISSUE THREAD

**Issue by marko-kriskovic** [bytechefhq/bytechef#974]
### Describe the bug

when I want to change an action the UI changes, but it remains the same in the workflow. Refreshing the page resets the UI to the unchanged action.

### Steps To Reproduce

1. create a component
2. assign an action
3. open the Edit Workflow to see the real state (optional)
4. refresh the page

### Expected behavior

Users should be allowed to change actions

### Version

latest

### OS

ubuntu

**Comment by kresimir-coko** [comment]
https://github.com/bytechefhq/bytechef/pull/978
